name: ci

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build Lib
        run: npm run build
      - name: Build Demo
        run: npm run build-demo
      - name: Publish to GitHub Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }} # see the Configuration section for how you can create secrets
          angular_project_dir: projects/ngx-color-palette-selector-app/
          base_href: /ngx-color-palette-selector/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          deploy_branch: gh-pages # The branch the action should deploy to.
          angular_dist_build_folder: dist/ngx-color-palette-selector-app # The folder where your project is supposed to be after running ng build by the action.
